"""Automated migration script

Revision ID: 450dc6528e92
Revises: 
Create Date: 2025-07-28 14:07:16.098378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450dc6528e92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('pes_lead', sa.Text(), nullable=True),
    sa.Column('client_name', sa.Text(), nullable=True),
    sa.Column('project_stage', sa.Text(), nullable=True),
    sa.Column('project_scope', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('expected_end_date', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('location_district', sa.Text(), nullable=True),
    sa.Column('dam_type', sa.Text(), nullable=True),
    sa.Column('avg_annual_inflow_mcm', sa.Text(), nullable=True),
    sa.Column('gross_storage_mcm', sa.Text(), nullable=True),
    sa.Column('live_storage_mcm', sa.Text(), nullable=True),
    sa.Column('ncl_m', sa.Text(), nullable=True),
    sa.Column('dam_weir_height_m', sa.Text(), nullable=True),
    sa.Column('crest_elevation', sa.Text(), nullable=True),
    sa.Column('flood_q_cms', sa.Text(), nullable=True),
    sa.Column('power_mw', sa.Text(), nullable=True),
    sa.Column('cca_hectare', sa.Text(), nullable=True),
    sa.Column('canal_q_cms_drinking_water_supply', sa.Text(), nullable=True),
    sa.Column('catchment_area_sqkm', sa.Text(), nullable=True),
    sa.Column('sediment_load_m3_sqkm_yr', sa.Text(), nullable=True),
    sa.Column('project_cost_m_rs', sa.Text(), nullable=True),
    sa.Column('survey_status', sa.Text(), nullable=True),
    sa.Column('gi_status', sa.Text(), nullable=True),
    sa.Column('additional_description', sa.Text(), nullable=True),
    sa.Column('last_updated_at', sa.Text(), nullable=True),
    sa.Column('last_updated_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('project_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('update_text', sa.Text(), nullable=False),
    sa.Column('status_progress_text', sa.Text(), nullable=True),
    sa.Column('status_color', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('update_display_date', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_updates')
    op.drop_table('projects')
    # ### end Alembic commands ###
